### ISSUE TITLE
Attempt to call a nil value error on Lua

### ISSUE THREAD

**Issue by haath** [haxe-utest/utest#102]
Hey, I am trying to run tests for the lua target, and I am getting the following error:

```
 lua: build/lua/test.lua:1106: attempt to call a nil value (method 'lastIndexOf')
 stack traceback:
 	build/lua/test.lua:1106: in field 'startsWith'
 	build/lua/test.lua:8435: in method 'isTestFixtureName'
 	build/lua/test.lua:8361: in method 'addITest'
 	build/lua/test.lua:8343: in method 'addCase'
 	build/lua/test.lua:1198: in field 'main'
 	build/lua/test.lua:10096: in main chunk
 	[C]: in ?
```

The same tests run fine with the rest of the targets, `cpp`, `neko`, `hl`, `js` etc.

The full build: https://gitlab.com/haath/bytetype/-/jobs/578696044

The tests folder in question: https://gitlab.com/haath/bytetype/-/tree/master/test

**Comment by RealyUniqueName** [comment]
Looks like a bug of the Lua target. Removing `--no-inline` fixes it.

**Comment by RealyUniqueName** [comment]
https://github.com/HaxeFoundation/haxe/issues/9530

**Comment by haath** [comment]
That was it, thanks :)
