### ISSUE TITLE
async on setup

### ISSUE THREAD

**Issue by postite** [haxe-utest/utest#11]
hello @fponticelli ,
i was testing some stuff with zombie.js (https://github.com/assaf/zombie/blob/master/README.md)
i get the Assert.createAsync stuff but i would like to know if it's possible to do some async setup.

function setup(p):Void
    {
        zombie = new Zombie();

```
     //Zombie.localhost("localhost",8888);
    // untyped zombie.dump();
     done = Assert.createAsync();
     zombie.visit("http://localhost:8888/index.php",function(e){

        // make here a call to testAsync1, testAsync2 etc...

        done();
    }
    );

}

public function testAsync1(){

        Assert.equals("poupidou",zombie.text("p"));     

}
public function testAsync2(){

        Assert.equals("poupidou",zombie.text("p"));     

}
```

Do you get what i mean ?
thx

**Comment by fponticelli** [comment]
I do and I see the value ... we can certainly think about patching utest to support it. A workaround for now (not super nice) is to do all the prep outside the tests and fire them once you are ready?

**Comment by postite** [comment]
by outside do you mean something like this ?

var runner:Runner;
    public function new()
    {

```
    runner = new Runner();
    Report.create(runner);
    zombify();



}
function zombify():Void
{
    var zombie = new Zombie();
    zombie.visit("http://localhost:8888/index.php",function(e){
    runner.addCase(new TestBof(zombie));
    runner.run();
        });
}
```

that work!  ... thx

**Comment by fponticelli** [comment]
yup, something like that :)
