### ISSUE TITLE
Deprecated Assert.is method in the documentation

### ISSUE THREAD

**Issue by khalyomede** [haxe-utest/utest#110]
## Description

The documentation mentions `Assert.is()`, but the compilation suggest to use isOfType

> Warning : utest.Assert.is is deprecated. Use utest.Assert.isOfType() instead

## Expected behavior

The documentation mentions `Assert.isOfType()` instead of `Assert.is()`

**Comment by player-03** [comment]
Where in the documentation? A quick search turned up no documentation mentioning the string `Assert.is(`. Or, for that matter, the string `Assert.isOfType(`.

**Comment by RealyUniqueName** [comment]
This is handled in #124 
https://github.com/haxe-utest/utest/blob/9a5ea19d85b5f7c2a3ea735b5bfac41e3cd714e1/src/utest/Assert.hx#L101-L102
