### ISSUE TITLE
php target is broken

### ISSUE THREAD

**Issue by acarioni** [haxe-utest/utest#112]
**Environment**
macOS monterey 12.1
haxe 4.2.4
utest 1.13.2
PHP 8.1.1

The code generated for php target is broken.
The issue can be reproduced by compiling the following class with the command `haxe --main foo.TestAll --php php  --library utest` and by running the generated file index.php with `php index.php`

```
//TestAll.hx
package foo;

import utest.Runner;

class TestAll {
  public static function main() {
    var runner = new Runner();
    runner.run();
  }
}
```

The error reported is 

> PHP Fatal error:  During inheritance of JsonSerializable: Uncaught ErrorException: Return type of Array_hx::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/foobar/temp/php/lib/Array_hx.php:270
> Stack trace:
> #0 /Users/foobar/temp/php/lib/Array_hx.php(11): php\Boot::php\{closure}(8192, 'Return type of ...', '/Users/foobar...', 270)
> #1 /Users/foobar/temp/php/index.php(10): include_once('/Users/foobar...')
> #2 /Users/foobar/temp/php/lib/utest/Runner.php(109): {closure}('Array_hx')
> #3 /Users/foobar/temp/php/lib/foo/TestAll.php(16): utest\Runner->__construct()
> #4 /Users/foobar/temp/php/index.php(15): foo\TestAll::main()
> #5 {main} in /Users/foobar/temp/php/lib/Array_hx.php on line 11
> 
> Fatal error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of Array_hx::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/foobar/temp/php/lib/Array_hx.php:270
> Stack trace:
> #0 /Users/foobar/temp/php/lib/Array_hx.php(11): php\Boot::php\{closure}(8192, 'Return type of ...', '/Users/foobar...', 270)
> #1 /Users/foobar/temp/php/index.php(10): include_once('/Users/foobar...')
> #2 /Users/foobar/temp/php/lib/utest/Runner.php(109): {closure}('Array_hx')
> #3 /Users/foobar/temp/php/lib/foo/TestAll.php(16): utest\Runner->__construct()
> #4 /Users/foobar/temp/php/index.php(15): foo\TestAll::main()
> #5 {main} in /Users/foobar/temp/php/lib/Array_hx.php on line 11
> /usr/local/lib/haxe/lib/utest/1,13,2/src/utest/ui/Report.hx:21: characters 10-13 : Warning : php.Web is deprecated and will be removed from standard library. See php.SuperGlobal and php.Global for alternatives.
> Error: Command failed with error 255
>

**Comment by RealyUniqueName** [comment]
This is a Haxe's issue. See https://github.com/HaxeFoundation/haxe/issues/10502
