### ISSUE TITLE
considerations for v2

### ISSUE THREAD

**Issue by fponticelli** [haxe-utest/utest#14]
# Breaking Changes
## `Assert.createAsync`

It will be removed, and replaced by more flexible signatures of tests cases:

``` haxe
class Test {
  @:timeout(500) // defaults to 200ms
  public function testAsync(done : Void -> Void) {
    // make sure to invoke done() at the end of the test
  }

  public function testPromise() : Promise<Nil> { ... }
  public function testFuture() : Future<Nil> { ... }
}
```
# New Features
## Analyze Test Classes at compile time

``` haxe
runner.registerClass(Test); // no need to instantiate Test
```
## asynchronous setup/teardown

Same features as standard tests
## add setupInstance/teardownInstance

Add setup/teardown that run once per instance instead of once per method.
### @:timeout(time)

Set the acceptable timeout for test methods
### @:setup/setupInstance

Marks a method as a setup method
### @:teardown/teardownInstance

Marks a method as a teardown method
### @:test(?description)

Marks a method as a test case
### @:spec

Marks a method as a spec test. A spec test takes all the `==` (and other comparison operators) and transform them into asserts.

**Comment by RealyUniqueName** [comment]
Any opinions?
