### ISSUE TITLE
Float as Int

### ISSUE THREAD

**Issue by wighawag** [haxe-utest/utest#22]
Hi, 

I hit another hiccup with Assert.same and it is because the way Haxe own Type.typeOf works for Number (at least in js):
https://github.com/HaxeFoundation/haxe/blob/development/std/js/_std/Type.hx#L157

I basically have a json file as test data and it contains float (like 6.0)
It is then parsed using -D HaxeJson and have a value of 6

Then in same it check type first using Type.typeof which return TInt in that case. it then use the int equality as opposed to the expected float equality

I hope that make sense

I am not sure where the error lies here. We could argue that Type.typeOf should never return TInt in js as in js there is no Int but it would be weird to have a variable typed as Int returning Float?

Would there be a way to get arround that issue in utest ?

Maybe by considerring int and float similarly (at least for Assert.same) ?

What do you think?

**Comment by fponticelli** [comment]
So essentially you are saying that `6` is never equals to `6.0000000000001` when using `same`? If that is the case I think you are right and in `same` we should use float equality everywhere.

**Comment by wighawag** [comment]
yes

**Comment by fponticelli** [comment]
I will gladly appreciate a PR :)

**Comment by RealyUniqueName** [comment]
Fixed in #23
