### ISSUE TITLE
Tests should return true/false

### ISSUE THREAD

**Issue by indolering** [haxe-utest/utest#25]
I have a lot of tests that cascade, so it doesn't make sense to test if the first test fails.  I do a lot of parameterized testing so the additional failures create a lot of noise when the test fails.

Right now I must basically test the condition first, save it to a variable, and then run isTrue for every test.  It would be ideal if the tests just returned true/false to indicate passing, which I could save to a variable and use as a conditional later.

**Comment by fponticelli** [comment]
you mean that the `Assert` methods should return a `Bool` or the test case methods? If it is the latter, how would you catch that result? The invocation of test methods is automatically performed by utest.

**Comment by indolering** [comment]
It should return a boolean.

**Comment by indolering** [comment]
Another option would be for tests to alter a global indicating that a test failed and then parametrize the ability to stop tests after a suite has failed.

**Comment by T1mL3arn** [comment]
> stop tests after a suite has failed.

`munit` runs its tests in a similar way. If there was a fail in a test method then all asserts after the failed one will not be checked.

**Comment by RealyUniqueName** [comment]
`utest.Assert` methods now return `true` on success and `false` on failure.
`@:depends` meta can be used to define dependencies for a test ([readme](https://github.com/haxe-utest/utest/blob/6f1d599a818e8bd7c695ada8dd0ba8846652e971/README.md#inter-test-dependencies))
