### ISSUE TITLE
Add a global mechanism for filtering which tests are run

### ISSUE THREAD

**Issue by ghost** [haxe-utest/utest#26]
Sometimes I just want to run a single test to debug something without running other tests.

Runner .addCase lets you specify a pattern per test class.  Maybe runner could also let you specify a global pattern that overrides all other patterns, like `runner.setPattern(~/testMyTest/)`.

Or, each test function could have a `@:only` metadata, and if there are any functions with `@:only`, the runner only runs those?

**Comment by mboussaa** [comment]
also it would be great to be able to run the same test case many times, because actually it is not possible to add same test case several times
