### ISSUE TITLE
Async setup & Suite setup

### ISSUE THREAD

**Issue by fantoine** [haxe-utest/utest#28]
Hi,

I'm using utest for a nodejs project and I would like to be able to implement async suite setups.

I already simulated a 'suite setup' by counting each call to `setup` and calling a custom `setupSuite` method on first `setup` call.

However I have some trouble to get my async setup call.
I have some async database manipulations to run on my `setupSuite` and use `Assert.createAsync` to try to 'lock' the call to the tests, but it doesn't seem to work.

Is there a way to achieve this?

**Comment by fponticelli** [comment]
Unfortunately `setup` and `teardown` are inherently synchronous. I really need to start working utest 2 but in the meanwhile the easiest solution might be to add support for `setupAsync` and `teardownAsync` and integrate them in the process. They should take a `Void -> Void` callback to signal that they did what they were supposed to do. A PR would be greatly appreciated :)
