### ISSUE TITLE
1.1.0 haxelib release contains "src" folder

### ISSUE THREAD

**Issue by andyli** [haxe-utest/utest#3]
Thanks for the haxe3 compatible release, but haxelib doesn't like the extra level of "src" folder, which the utest package should be at root level. ;)

**Comment by fponticelli** [comment]
oops ... bad packaging ... going to fix it.

**Comment by fponticelli** [comment]
Should be fine now ... please let me know.

**Comment by andyli** [comment]
Yes, it is perfect now! Thanks!
