### ISSUE TITLE
Async tests on other than flash or js targets

### ISSUE THREAD

**Issue by RealyUniqueName** [haxe-utest/utest#33]
Is this really needed now when `haxe.Timer` is implemented on all platforms?
https://github.com/fponticelli/utest/blob/master/src/utest/TestHandler.hx#L62

I have async tests which fail untill i change `#if (flash || js)` to `#if (neko || flash || js)`

**Comment by fponticelli** [comment]
Is `Timer.delay` implemented for all platforms? I think Nicolas planned on that but is it done?

**Comment by RealyUniqueName** [comment]
It is https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/Timer.hx#L136

**Comment by fponticelli** [comment]
Cool, I will tests it ASAP.
