### ISSUE TITLE
No test result message on cpp target

### ISSUE THREAD

**Issue by DleanJeans** [haxe-utest/utest#34]
When I run a test on cpp with something like this `.hxml`:
```
-cp hscript
-cp plus/test
-lib utest
-main TestAll
-cpp plus/bin/test-cpp

-cmd start plus/bin/test-cpp/TestAll.exe
```
I got nothing at all. Maybe just a warning from `$type()`.
I hardly found some `.hxml` targetting cpp on the internet.

**Comment by romanmikhailov** [comment]
Hi @DleanJeans
Can you provide a minimal example of project with issue to allow us to check?
Thank you!

**Comment by RealyUniqueName** [comment]
That's because `start` command launches your exe in a separate process, thus your terminal does not get stdout of your app.
Try this:
```
-cmd plus/bin/test-cpp/TestAll.exe
```
