### ISSUE TITLE
utest for Haxe 3 ?

### ISSUE THREAD

**Issue by yanhick** [haxe-utest/utest#4]
Hi Franco,
this is Yannick from SilexLabs, how do you do ?

I'm upgrading cocktail to Haxe 3 and I use utest, it doesn't seem available on haxelib. Do you  plan to release it at some point ?

I tried to make it work from your repo, it builds but it don't seem to run.

Thanks for the great work

**Comment by fponticelli** [comment]
I released a new version for Haxe3 (http://lib.haxe.org/p/utest).
Are you using the new haxelib?

**Comment by yanhick** [comment]
Well I tried again and you're right it works ! I must have made a spelling mistake.
Sorry to have bothered you for nothing, thanks.

**Comment by fponticelli** [comment]
No worries, I am glad you are using the lib ;)

**Comment by yanhick** [comment]
It's our pleasure, we always need good tests :)
