### ISSUE TITLE
[Discussion] `Runner.addCase` pattern seems to be inconsistent.

### ISSUE THREAD

**Issue by romanmikhailov** [haxe-utest/utest#42]
Question related to patterns in `Runner.addCase`.

Why `Runner.addCase` function argument pattern doesn't override `globalPattern`?

https://github.com/fponticelli/utest/blob/master/src/utest/Runner.hx#L102

It will be more logical that more narrow declaration override more global declaration, not vice versa, isn't it?

Should this condition be rewrited as `if (pattern == null) pattern = globalPattern;`?

As for me `globalPattern` should have global policy, meanwhile `pattern` in `addCase` should allow to change global behavior.

@fponticelli What do you think?

**Comment by fponticelli** [comment]
Yes, that makes sense. I believe you are right.

**Comment by romanmikhailov** [comment]
Add pull request for this change https://github.com/fponticelli/utest/pull/44/files
