### ISSUE TITLE
Runner#addCases by package does not filter duplicates

### ISSUE THREAD

**Issue by romanmikhailov** [haxe-utest/utest#49]
I occasionally specify class paths arguments `-cp` twice and receive failed tests related to latest Runner#addCases functionality.

```
> haxe -cp src -cp test -cp test -main TestAll -D utest -D exit -D unsafe -dce std -debug -cs bin/test-cs
> mono --debug bin/test-cs/bin/TestAll-Debug.exe
```

```
results: SOME TESTS FAILURES (success: false)
utest.TestRunner
  testAddCases_identifier: FAILURE F
    line: 21, expected 3 but it is 6
  testAddCases_notRecursive: FAILURE F
    line: 9, expected 2 but it is 4
  testAddCases_recursive: FAILURE F
    line: 15, expected 3 but it is 6
```

I think there should be duplicates filtering inside.
@RealyUniqueName What do you think?

**Comment by RealyUniqueName** [comment]
I'm not sure it should filter duplicates. One can call `runner.addCases(path)` multiple times as well.
I think it's a user's responsibility to properly add test cases to a test runner. 
Otherwise we need to make ordinary `addCase` to also filter duplicates to keep things consistent.

**Comment by romanmikhailov** [comment]
Probably there should be some warning?

**Comment by RealyUniqueName** [comment]
That sounds more like a responsibility of a compiler. Perhaps it's worth to submit an issue to the compiler repo.
I'm closing this issue because i doubt we should do anything regarding duplicates.
Feel free to reopen if you are strongly convinced we should.
