### ISSUE TITLE
[CI] Update Travis, Appveyor and SouceLabs for haxe-utest organization

### ISSUE THREAD

**Issue by romanmikhailov** [haxe-utest/utest#50]
@fponticelli Please re-attach this repository into travis. Because travis link lead to webpage with error popup. 

```
We couldn't find the repository 
fponticelli/utest
```

**Comment by RealyUniqueName** [comment]
I've updated Travis setup. Will do Appveyor and  SauceLabs later.

**Comment by romanmikhailov** [comment]
OK

**Comment by RealyUniqueName** [comment]
@fponticelli Appveyor doesn't list this repository for me. Maybe it's because this repo is already tied up with your appveyor account. Do you know how can we setup appveyor?

**Comment by fponticelli** [comment]
Not really, I deleted it with the intention to recreate it but it is now gone from the list of services.

**Comment by RealyUniqueName** [comment]
Appveyor is set up now.

**Comment by romanmikhailov** [comment]
@RealyUniqueName  Appveyor runs tests only on latest stable release of haxe (Now it's 3.4.4).
What about development as on travis?

**Comment by RealyUniqueName** [comment]
I'm not sure when i'll be able to do it. PR is welcome )

**Comment by RealyUniqueName** [comment]
Moved to github-actions
