### ISSUE TITLE
Running large amount of tests failed with StackOverflow on nodejs

### ISSUE THREAD

**Issue by romanmikhailov** [haxe-utest/utest#52]
Necessary (to reproduce) amount of tests are different on different machine configurations.

And it results in failing with adding the same erro test result in 
https://github.com/haxe-utest/utest/blob/master/src/utest/ui/common/ClassResult.hx#L27
```
invalid duplicated fixture: TestCase#test12311
```

haxe: 3.4.2, 3.4.4
utest: latest (and I think that this was before but I have latest)

**Comment by fnaith** [comment]
also failed on C# target, haxe 3.4.4, utest cf5460e

runner add 28 case, contains about 1500~1600 asserts.

**Comment by RealyUniqueName** [comment]
Can you check this with the latest changes?

**Comment by fnaith** [comment]
It works to my cs targeting project in haxe 3.4.7 (for now). case number as following :

> PrintReport.hx:52:
> assertations: 1963
> successes: 1961
> errors: 0
> failures: 2
> warnings: 0
> execution time: 0

Well... later better than never. Thanks for fixing this issue :P

**Comment by RealyUniqueName** [comment]
Thanks for the report )
