### ISSUE TITLE
Looks like for several targets reports are not very accurate.

### ISSUE THREAD

**Issue by romanmikhailov** [haxe-utest/utest#53]
Look at output of latest self-tests running:
https://travis-ci.org/haxe-utest/utest/jobs/318686593

Reports are different for different targets.
I think it can impact also on execution of async tests.

Compare neko and nodejs:
```
assertations: 54
successes: 54
errors: 0
failures: 0
warnings: 0
execution time: 0.027
results: ALL TESTS OK (success: true)
```

```
assertations: 55
successes: 55
errors: 0
failures: 0
warnings: 0
execution time: 0.131
results: ALL TESTS OK (success: true)
```

I think it can be caused by difference in running on these targets:
https://github.com/haxe-utest/utest/blob/master/src/utest/Runner.hx#L182

**Comment by RealyUniqueName** [comment]
Yep, it is. Will be addressed with #56
