### ISSUE TITLE
[js] uncaught exception: invalid duplicated fixture

### ISSUE THREAD

**Issue by T1mL3arn** [haxe-utest/utest#54]
I've got this error
```haxe
uncaught exception: invalid duplicated fixture: TestCase.testFoo
```
Code to reproduce
```Haxe
import utest.*;
import utest.ui.*;

class Main {
    static function main() {
        var runner = new Runner();
        runner.addCase(new TestCase());
        Report.create(runner);
        runner.run();
    }
}

@:keep
class TestCase{
    public function new() {}

    public function testFoo(){
        Assert.isTrue(true);
        Assert.isFalse(false);
        Assert.fail('A');    // without this fail()
        Assert.warn("WARNING"); // and without this warn() there is no error
    }
}
```
build.hxml file
```haxe
-cp src
-lib utest
-dce std
-D analyzer-optimize
-main Main
-js bin/out.js
# --interp
```
Tested on both haxe version 3.4.2 and 3.4.7
utest version is 1.8.0
## Some notes
Exception throws if there is `Assert.warn()` or `Assert.fail()`. With no those all is perfect.
`dce` and `analyzer-optimize` have no affect on result. If we replace `js` target on `interp` there is also no error. 

This issue can be related to this #52 due the same error.

**Comment by RealyUniqueName** [comment]
I can't reproduce it with the same uitest and haxe versions.

**Comment by T1mL3arn** [comment]
It can be reproduced with this HTML page
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="index.js"></script>
</head>
<body>
    <!-- <script src="index.js"></script> -->
</body>
</html>
```
Note script tag in head tag. If we move that script tag into body then there will be no error. Thus, problem is in html reporter. Should the reporter do check ```Document.readyState``` before running tests?
