### ISSUE TITLE
Cannot build documentation - syntax error for java

### ISSUE THREAD

**Issue by T1mL3arn** [haxe-utest/utest#58]
I've got this error while trying to build documentation (by `hxml` from `doc/` fodler)
```cmd
C:\HaxeToolkit\utest/git/src/utest/ui/text/HtmlReport.hx:712: characters 4-7 : Type not found : Lib
Error: Command failed with error 1
```
Seems `java` target there is an unnecessary one, cause `java.Lib` does not have `print()` method
https://github.com/haxe-utest/utest/blob/99fec3f6b7e246d79762257d47866fba034b4493/src/utest/ui/text/HtmlReport.hx#L710-L713
Should `java` be removed or replaced with `trace()` or similar?

**Comment by RealyUniqueName** [comment]
The easiest is probably to just remove `java` here.
Need to check if `Lib.print()` is justified here or it should be replaced with `trace()`
