### ISSUE TITLE
delay for closing swf

### ISSUE THREAD

**Issue by postite** [haxe-utest/utest#8]
hello franco! 
i just tried utest today ..
it could be useful to set delay in PlainTextReport as a variable...
5 seconds is a bit short ... :)
personnaly i did 

if(flash.system.Security.sandboxType == "localTrusted") {
        var delay = Runner.delay;
        trace('all done, exiting in $delay seconds');
        haxe.Timer.delay(function() try {
            flash.system.System.exit(result.stats.isOk ? 0 : 1);
          } catch(e : Dynamic) {
            // do nothing
          }, delay \* 1000);
      }

**Comment by ponticelli** [comment]
I am not sure it belongs to Runner but I agree that it would be good to be easily configured from outside. Another thing I was considering is to put a -D noexit to prevent the behavior entirely. I am trying to make the exit work correctly in Travis but after all of my attempts it still never exit :(

**Comment by RealyUniqueName** [comment]
wontfix because flash
