### ISSUE TITLE
Multiple async calls

### ISSUE THREAD

**Issue by Aurel300** [haxe-utest/utest#94]
In `haxe-sys` tests I use the following setup:

https://github.com/Aurel300/haxe-sys/blob/f3b24404315a83f390513ad44d03023f8237074e/tests/test/Test.hx#L12-L38

Then in tests:

```haxe
function testSomething(async:Async) {
  sub(async, done -> {
    // ...
    somethingAsynchronous(() -> done());
  });
  sub(async, done -> {
    differentAsynchronousThing(() -> done());
  });
}
```

This is convenient when doing performing multiple asynchronous tasks, which may finish at different times, but are either connected (e.g. a client + server test), or at least related (convenient to place them under a single "test"). It counts how many calls to `done` are expected and how many calls actually arrive.

Could there be a similar API accessible on `Async` directly?

**Comment by RealyUniqueName** [comment]
What about these additional methods for `utest.Async`?
```haxe
/**
    Set the amount of times `async.done()` should be called for this async to be resolved.
**/
public function setDoneCount(count:Int):Void;
/**
    Resolve this async no matter how many times `async.done()` was called.
**/
public function allDone():Void;
```
or / and
```haxe
/**
   Create a sub-async. Current `Async` instance will be resolved automatically once all sub-asyncs are resolved.
**/
public function branch():Async;
```

**Comment by Aurel300** [comment]
`branch` seems like the more useful one, since having to keep track of the done count manually could be tedious and prone to errors.

Personally I would prefer an API like:

```haxe
public function branch(f:Async->Void):Void;
```

Where `f` is invoked immediately with the "branched" `Async`.

```haxe
var doneSignalAsync = async.branch();
var dataSignalAsync = async.branch();
something.doneSignal.on(() -> doneSignalAsync.done());
something.dataSignal.on(() -> dataSignalAsync.done());
// vs
async.branch(async -> {
  something.doneSignal.on(() -> async.done());
});
async.branch(async.done -> {
  something.dataSignal.on(() -> async.done());
});
```

Less work having to think of new names :)

If there is a done count as well, then it could be an optional argument for `branch`.

**Comment by RealyUniqueName** [comment]
Looks like a way to callback hell )

**Comment by Aurel300** [comment]
Well yes, but what else do you want to do with callback-centric code? It will be nicer with coroutines but we need some underlying API anyway.
